# Generated by Django 4.2.11 on 2024-05-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=2000)),
                ('shortened_url', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
