# Generated by Django 4.2.11 on 2024-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortening', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
