# Generated by Django 4.2.11 on 2024-05-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortening', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='user',
            new_name='owner',
        ),
    ]
