# Generated by Django 4.2.11 on 2024-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortening', '0003_alter_url_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='customized',
            field=models.BooleanField(default=False, help_text='Designates whether the shortened slug is customized or not.', verbose_name='Customized URL'),
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(max_length=2000),
        ),
    ]
