# Generated by Django 5.2.3 on 2025-06-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="staff",
            new_name="is_staff",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_url_created",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="premium_user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="total_urls",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="website",
        ),
        migrations.RemoveField(
            model_name="url",
            name="expired",
        ),
        migrations.RemoveField(
            model_name="user",
            name="admin",
        ),
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("guest", "Guest"), ("free", "Free")],
                default="free",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="url",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the shortened URL will expire.",
                null=True,
                verbose_name="Expiration date",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the shortened slug is active or not. Unselect this instead of deleting records.",
                verbose_name="Active status",
            ),
        ),
    ]
