# Generated by Django 5.2.3 on 2025-06-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_url_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_type",
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("guest", "Guest"), ("free", "Free")],
                default="free",
                max_length=10,
            ),
        ),
    ]
