# Generated by Django 5.2.3 on 2025-07-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_profile_user_type_user_user_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SlotTracker",
        ),
    ]
