# Generated by Django 5.2.3 on 2025-07-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_delete_slottracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="click",
            name="redirected",
            field=models.BooleanField(default=False),
        ),
    ]
