# Generated by Django 4.2.11 on 2024-04-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('url_shortening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shortening.url'),
        ),
    ]
